name: Print RUN successful

# Trigger the workflow on any push or pull request
on:
  push:
    branches:
      - main 
      - test
      - test2 # You can specify the branches to trigger on
  pull_request:
    branches:
      - main

jobs:
  print-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print success message
        run: echo "RUN successful"
